apiVersion: v1
kind: Service
metadata:
  name: expressjs
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: expressjs
  sessionAffinity: None
  type: ClusterIP
